global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load rules from files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configs
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'demo-generator'
    static_configs:
      - targets: ['demo-generator:8000']
